<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IMPERIUS" failures="2" tests="20" name="Real_Project.First_Real_Program" time="0.361" errors="0" timestamp="2024-06-19T11:08:36 CEST" skipped="2">
  <testcase classname="Real_Project.First_Real_Program" name="Counter" time="0.004"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.014"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="verifyTitle" time="0.028"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="verifyLogo" time="0.084">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Real_Project.First_Real_Program.verifyLogo(First_Real_Program.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- verifyLogo -->
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionBrokenlinks" time="0.002">
    <skipped/>
  </testcase> <!-- AdmissionBrokenlinks -->
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.004"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionBrokenlinks" time="0.046">
    <skipped/>
  </testcase> <!-- AdmissionBrokenlinks -->
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="verifyTitle" time="0.012"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.004"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.001"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.003"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="verifyLogo" time="0.134">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Real_Project.First_Real_Program.verifyLogo(First_Real_Program.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- verifyLogo -->
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.001"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="Counter" time="0.001"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.013"/>
  <system-out/>
  <testcase classname="Real_Project.First_Real_Program" name="AdmissionLogin" time="0.002"/>
  <system-out/>
</testsuite> <!-- Real_Project.First_Real_Program -->
